### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by Grzyb9k** [touhidurabir/laravel-model-repository#1]
When i run command to make repository i got:

Exception Arise During Task Execution
Exception : mkdir(): No such file or directory - C:\work\projects\aurum\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php at line 600

**Comment by touhidurabir** [comment]
@Grzyb9k I will look into it as it's works for me in both of my mac and ubuntu machine . However can you please provide your laravel and php version ? 

also are you are you using the default **repositories_namespace** defined in the config file or passing a custom class namespace path like 

```bash
php artisan make:repository App\\SomeOtherPath\\SomeRepositoryClass
```

or if you have defined a custom **repositories_namespace** in the config file ?

**Comment by touhidurabir** [comment]
@Grzyb9k after some good amount of testing and even updating the tests of the package to test more edge cases , I could not produce the issue that you are facing . I may be able to help you a bit more if I get the details that I have asked in my previous comment .

**Comment by touhidurabir** [comment]
I think the issue was originated form another one my package(https://github.com/touhidurabir/laravel-stub-generator) that used internally to generate class files from the stub when used in windows system . As that bug is fixed for windows in the mentioned package , it should be fine now . So I am closing this issue .
